  language: generic
  sudo: required
  
  services:
    - docker
  
  before_install:
    - docker build -t grumpygk/docker-react -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true grumpygk/docker-react npm run test
    